apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml --profile all
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml --profile all
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_ENABLED
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: api-gateway
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: api-gateway:8080
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
            - name: JAVA_OPTS
              value: -Xmx192m -Xms96m -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_APPLICATION_NAME
              value: api-gateway
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
            - name: SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL
              value: "3000"
            - name: SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS
              value: "20"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8888
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: meriemabboud/ecommerce-microservices-api-gateway:latest  # Changed this line
          imagePullPolicy: Always  # Add this line to match other services
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/actuator/health
            failureThreshold: 5
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 15
          name: api-gateway
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: "268435456"
      restartPolicy: Always