apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml --profile all
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml --profile all
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: config-server
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_ENABLED
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: config-server
            - name: EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS
              value: "90"
            - name: EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS
              value: "30"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
            - name: JAVA_OPTS
              value: -Xmx128m -Xms64m -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
            - name: SPRING_CLOUD_CONFIG_SERVER_HEALTH_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS
              value: file:/config-repo/,classpath:/config/
            - name: SPRING_PROFILES_ACTIVE
              value: native
          image: ecommerce-microservices-config-server:latest  # Changed this line
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8888/actuator/health
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
          name: config-server
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: "201326592"
          volumeMounts:
            - mountPath: /config-repo
              name: config-server-claim0
      restartPolicy: Always
      volumes:
        - name: config-server-claim0
          persistentVolumeClaim:
            claimName: config-server-claim0