apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml --profile all
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: eureka-server
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eureka-server
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.yml --profile all
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: eureka-server
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_TRANSPORT_CONNECT_TIMEOUT_MS
              value: "8000"
            - name: EUREKA_CLIENT_TRANSPORT_READ_TIMEOUT_MS
              value: "8000"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: eureka-server
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
            - name: EUREKA_SERVER_ENABLE_SELF_PRESERVATION
              value: "true"
            - name: JAVA_OPTS
              value: -Xmx128m -Xms64m -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC
            - name: SERVER_PORT
              value: "8761"
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          # FIXED: Updated image name to match your actual Docker image
          image: ecommerce-microservices-eureka-server:latest
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8761/actuator/health
            failureThreshold: 5
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 10
          name: eureka-server
          ports:
            - containerPort: 8761
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: "268435456"
      restartPolicy: Always