apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml --profile all
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: notification-service
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notification-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml --profile all
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: notification-service
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_ENABLED
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: notification-service
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: notification-service:8087
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
            - name: JAVA_OPTS
              value: -Xmx128m -Xms64m -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC
            - name: SPRING_APPLICATION_NAME
              value: notification-service
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
            - name: SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL
              value: "3000"
            - name: SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS
              value: "20"
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://config-server:8888
            - name: SPRING_DATASOURCE_PASSWORD
              value: DmRj2003
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/notificationdb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          # FIXED: Updated image name to match your actual Docker image
          image: ecommerce-microservices-notification-service:latest
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8087/actuator/health
            failureThreshold: 5
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 15
          name: notification-service
          ports:
            - containerPort: 8087
              protocol: TCP
          resources:
            limits:
              cpu: 150m
              memory: "201326592"
      restartPolicy: Always