version: '3.8'

services:
  # Grafana - Main dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: lgtm-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - lgtm

  # Prometheus - Metrics storage
  prometheus:
    image: prom/prometheus:latest
    container_name: lgtm-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - lgtm

  # Loki - Log aggregation
  loki:
    image: grafana/loki:latest
    container_name: lgtm-loki
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - lgtm

  # Tempo - Distributed tracing
  tempo:
    image: grafana/tempo:latest
    container_name: lgtm-tempo
    ports:
      - "3200:3200"
      - "14268:14268"  # Jaeger ingest
      - "4317:4317"    # OpenTelemetry gRPC
      - "4318:4318"    # OpenTelemetry HTTP
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks:
      - lgtm

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: lgtm-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - lgtm

volumes:
  grafana-data:
  prometheus-data:
  loki-data:
  tempo-data:

networks:
  lgtm:
    driver: bridge